# Generated by Django 3.1.5 on 2021-06-08 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210608_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subCategory',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
